nav:
  - Home: index.md
  - Terms : common/terms.md
  - Built in:
      - Deployment:
          - builtin/deployment/index.md
          - Metadata: builtin/deployment/metadata.md
          - Spec:
             - builtin/deployment/spec/index.md
             - Containers: builtin/deployment/containers.md
          # - Spec - Containers : builtin/deployment/containers.md


      - Service: builtin/service.md
  - Argo:
      - Repo: argo/repo.md
  - Template: template.md

repo_name: userbradley/kubernetes-manifests-site
repo_url: https://github.com/userbradley/kubernetes-manifests-site
edit_uri: edit/master/docs/
site_name: Kubernetes Manifests
site_url: https://kubernetes.breadnet.co.uk
site_description: Kubernetes Manifest files and Examples


theme:
  name: material
  favicon: https://breadnet.co.uk/favicon.ico
  logo: https://breadnet.co.uk/favicon.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant # IDK
    - navigation.tracking #Anchor links
    - navigation.expand #Exapnds the navigation in the UI
    - content.code.annotate
   # - toc.integrate
     #- content.tabs.link
    # - navigation.top
    #- navigation.tabs #Puts the pages in to nice tabs at the top
   # - navigation.expand
   # - navigation.instant
    - search.share
    - search.highlight
   # - content.code.annotate # Adds code block annotations globally
    - navigation.indexes #Adds nice navigation


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true # Pretty check lists
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  #- git-revision-date-localized:
  #    type: iso_datetime
  #    enable_creation_date: true


extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://uk.linkedin.com/in/bradley-stannard
      name: My Linkedin
    - icon: fontawesome/brands/github-alt
      link: https://github.com/userbradley
      name: My Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:webmaster@breadnet.co.uk
    - icon: fontawesome/solid/file-lines #https://fontawesome.com/docs/web/setup/upgrade/whats-changed#icons-renamed-in-version-6
      link: https://breadnet.co.uk
      name: My Website
  generator: false