version: "1.0"
stages:
  - "clone"
  - "setup"
  - "docker"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "userbradley/kubernetes-examples"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"


  setup:
    type: parallel
    stage: setup
    steps:
      fly-env:
        title: "Fly API Env"
        stage: "setup"
        image: alpine
        commands:
          - export FLY_API_TOKEN=${{FLY_API_TOKEN}}
          - cf_export FLY_API_TOKEN

  prod-flyregistry-build:
    title: "PROD Fly Build"
    type: "build"
    working_directory: "${{clone}}"
    image_name: "dk8-manifests"
    tag: "${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "docker"
    registry: fly

  deploy-prod:
    title: "PROD Fly Deployment"
    stage: "deploy"
    image: "userbradley/flyctl:latest"
    working_directory: "${{clone}}"
    commands:
      - flyctl deploy --config k8-manifests.toml --image registry.fly.io/k8-manifests:${{CF_SHORT_REVISION}} --detach